# Generated by Django 5.1.2 on 2024-11-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_transaction_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='round_up_pot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('collect_roundup', 'Collect Roundup'), ('transfer', 'Transfer'), ('roundup_reclaim', 'Round Up Reclaim')], max_length=20),
        ),
    ]
