# Generated by Django 5.1.2 on 2025-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_round_up_pot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
